services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample_db
      PGDATA: /var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'user']
      interval: 5s
      timeout: 3s
      retries: 10
